// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package mysqlc

import (
	"database/sql"
)

type Coupon struct {
	Cno   string         `json:"cno"`
	Name  sql.NullString `json:"name"`
	Owner sql.NullString `json:"owner"`
}

type Task struct {
	ID          int32        `json:"id"`
	Description string       `json:"description"`
	StartDate   sql.NullTime `json:"start_date"`
	DueDate     sql.NullTime `json:"due_date"`
	Done        bool         `json:"done"`
	Deleted     bool         `json:"deleted"`
}
